import subprocess
from collections import OrderedDict

#Use an ordered dictionary so we can perform the quicker tests first
tests = OrderedDict()
#Add (testName, command) key-value pairs
tests['PartC-voting3']=['python', 
			r'C:\\Users\\George\\Documents\\VMSharedFolder\\EECS440PA2\\PA2\\PA2\\template\\python\\main.py',
			'--dataset_directory',
			'data',
			'--dataset',
			'volcanoes',
			'ann',
			'--gamma',
			'0.1',
			'--num_hidden',
			'3',
			'--layer_sizes',
			'1',
			'--max_iters',
			'10000']
tests['PartC-voting7']=['python', 
			r'C:\\Users\\George\\Documents\\VMSharedFolder\\EECS440PA2\\PA2\\PA2\\template\\python\\main.py',
			'--dataset_directory',
			'data',
			'--dataset',
			'volcanoes',
			'ann',
			'--gamma',
			'0.1',
			'--num_hidden',
			'7',
			'--layer_sizes',
			'1',
			'--max_iters',
			'10000']
tests['PartC-voting12']=['python', 
			r'C:\\Users\\George\\Documents\\VMSharedFolder\\EECS440PA2\\PA2\\PA2\\template\\python\\main.py',
			'--dataset_directory',
			'data',
			'--dataset',
			'volcanoes',
			'ann',
			'--gamma',
			'0.1',
			'--num_hidden',
			'12',
			'--layer_sizes',
			'1',
			'--max_iters',
			'10000']

tests['PartB-volcanoesIt100']=['python', 
			r'C:\\Users\\George\\Documents\\VMSharedFolder\\EECS440PA2\\PA2\\PA2\\template\\python\\main.py',
			'--dataset_directory',
			'data',
			'--dataset',
			'volcanoes',
			'ann',
			'--gamma',
			'0.1',
			'--num_hidden',
			'5',
			'--layer_sizes',
			'1',
			'--max_iters',
			'100']
tests['PartB-volcanoesIt325']=['python', 
			r'C:\\Users\\George\\Documents\\VMSharedFolder\\EECS440PA2\\PA2\\PA2\\template\\python\\main.py',
			'--dataset_directory',
			'data',
			'--dataset',
			'volcanoes',
			'ann',
			'--gamma',
			'0.1',
			'--num_hidden',
			'5',
			'--layer_sizes',
			'1',
			'--max_iters',
			'325']
tests['PartB-volcanoesIt550']=['python', 
			r'C:\\Users\\George\\Documents\\VMSharedFolder\\EECS440PA2\\PA2\\PA2\\template\\python\\main.py',
			'--dataset_directory',
			'data',
			'--dataset',
			'volcanoes',
			'ann',
			'--gamma',
			'0.1',
			'--num_hidden',
			'5',
			'--layer_sizes',
			'1',
			'--max_iters',
			'550']
tests['PartB-volcanoesIt775']=['python', 
			r'C:\\Users\\George\\Documents\\VMSharedFolder\\EECS440PA2\\PA2\\PA2\\template\\python\\main.py',
			'--dataset_directory',
			'data',
			'--dataset',
			'volcanoes',
			'ann',
			'--gamma',
			'0.1',
			'--num_hidden',
			'5',
			'--layer_sizes',
			'1',
			'--max_iters',
			'775']
tests['PartB-volcanoesIt1000']=['python', 
			r'C:\\Users\\George\\Documents\\VMSharedFolder\\EECS440PA2\\PA2\\PA2\\template\\python\\main.py',
			'--dataset_directory',
			'data',
			'--dataset',
			'volcanoes',
			'ann',
			'--gamma',
			'0.1',
			'--num_hidden',
			'5',
			'--layer_sizes',
			'1',
			'--max_iters',
			'1000']


tests['PartB-spamIt100']=['python', 
			r'C:\\Users\\George\\Documents\\VMSharedFolder\\EECS440PA2\\PA2\\PA2\\template\\python\\main.py',
			'--dataset_directory',
			'data',
			'--dataset',
			'spam',
			'ann',
			'--gamma',
			'0.1',
			'--num_hidden',
			'5',
			'--layer_sizes',
			'1',
			'--max_iters',
			'100']
tests['PartB-spamIt']=['python', 
			r'C:\\Users\\George\\Documents\\VMSharedFolder\\EECS440PA2\\PA2\\PA2\\template\\python\\main.py',
			'--dataset_directory',
			'data',
			'--dataset',
			'spam',
			'ann',
			'--gamma',
			'0.1',
			'--num_hidden',
			'5',
			'--layer_sizes',
			'1',
			'--max_iters',
			'550']
tests['PartB-spamIt1000']=['python', 
			r'C:\\Users\\George\\Documents\\VMSharedFolder\\EECS440PA2\\PA2\\PA2\\template\\python\\main.py',
			'--dataset_directory',
			'data',
			'--dataset',
			'spam',
			'ann',
			'--gamma',
			'0.1',
			'--num_hidden',
			'5',
			'--layer_sizes',
			'1',
			'--max_iters',
			'1000']



tests['PartC-volcanoes3']=['python', 
			r'C:\\Users\\George\\Documents\\VMSharedFolder\\EECS440PA2\\PA2\\PA2\\template\\python\\main.py',
			'--dataset_directory',
			'data',
			'--dataset',
			'volcanoes',
			'ann',
			'--gamma',
			'0.1',
			'--num_hidden',
			'3',
			'--layer_sizes',
			'1',
			'--max_iters',
			'22700']
tests['PartC-volcanoes110']=['python', 
			r'C:\\Users\\George\\Documents\\VMSharedFolder\\EECS440PA2\\PA2\\PA2\\template\\python\\main.py',
			'--dataset_directory',
			'data',
			'--dataset',
			'volcanoes',
			'ann',
			'--gamma',
			'0.1',
			'--num_hidden',
			'110',
			'--layer_sizes',
			'1',
			'--max_iters',
			'22700']
tests['PartC-volcanoes227']=['python', 
			r'C:\\Users\\George\\Documents\\VMSharedFolder\\EECS440PA2\\PA2\\PA2\\template\\python\\main.py',
			'--dataset_directory',
			'data',
			'--dataset',
			'volcanoes',
			'ann',
			'--gamma',
			'0.1',
			'--num_hidden',
			'227',
			'--layer_sizes',
			'1',
			'--max_iters',
			'22700']



#For each test
for fileName, args in tests.iteritems():
	if  '' in fileName:
		#Run the tests and capture its printouts
		result = subprocess.check_output(args)
		#Save the printouts to a file
		f = open(r'C:\\Users\\George\\Documents\\VMSharedFolder\\EECS440PA2\\PA2\\PA2\\template\\python\\tests\\'+fileName+'.txt', 'w')
		f.write(result)
		f.close()
		#Print out that this test has finished
		print fileName+' test is done '
